# Numpy

### GitHub repository: https://github.com/jorgemauricio/curso_itesm

### Instructor: Jorge Mauricio

In [3]:
# librerías
import numpy as np

# Crear Numpy Arrays
## De una lista de python
Creamos el arreglo directamente de una lista o listas de python

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## Métodos

### arange

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### ceros y unos
Generar arreglos de ceros y unos

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Generar un arreglo especificando un intervalo

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
Generar matrices de identidad

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
### rand
Generar un arreglo con una forma determinada de numeros con una distribución uniforme [0,1]

In [16]:
np.random.rand(2)

array([0.94379747, 0.98528007])

In [17]:
np.random.rand(5,5)

array([[0.72123868, 0.67398576, 0.03732775, 0.98790252, 0.31685183],
       [0.05030032, 0.97044383, 0.90947085, 0.65789465, 0.52080388],
       [0.0609048 , 0.02780601, 0.14588236, 0.0136128 , 0.41312919],
       [0.15149705, 0.70346254, 0.26413059, 0.68801579, 0.3763422 ],
       [0.77970615, 0.86250529, 0.09603077, 0.18166533, 0.37424322]])

### randn
Generar un arreglo con una distribucion estandar a diferencia de rand que es uniforme

In [18]:
np.random.randn(2)

array([-0.85404077, -1.86344941])

In [19]:
np.random.randn(5,5)

array([[-1.7425319 ,  0.40993789,  1.31562645, -0.86421398,  0.58854664],
       [-0.01667853,  1.76001509, -0.31376044, -0.69571795,  0.79840949],
       [ 0.7453972 ,  1.18270792,  0.2239688 ,  0.76193616, -0.78689124],
       [-2.08147966,  0.6600797 ,  0.05985255, -1.73611956,  1.7230851 ],
       [-1.17930009, -0.77854453, -1.78263598, -0.07224781, -0.13236782]])

### randint
Generar numeros aleatorios en un rango determinado

In [20]:
np.random.randint(1,100)

14

In [21]:
np.random.randint(1,100,10)

array([18, 34, 55, 65, 75, 42, 81, 86, 96, 90])

### Metodos y atributos de arreglos


In [22]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([14, 27, 34, 15, 31, 15, 38,  3, 39, 47])

### Reshape
Regresa el mismo arreglo pero en diferente forma

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin
Metodos para encontrar máximos y mínimos de los valores y sus indices

In [26]:
ranarr

array([14, 27, 34, 15, 31, 15, 38,  3, 39, 47])

In [27]:
ranarr.max()

47

In [28]:
ranarr.argmax()

9

In [29]:
ranarr.min()

3

In [30]:
ranarr.argmin()

7

### Shape
Atributo para desplegar la forma que tienen el arreglo

In [31]:
# Vector
arr.shape

(25,)

In [32]:
# Tomar en cuenta que se implementan dos corchetes
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25).shape

(1, 25)

In [34]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Despliega el tipo de dato de los objetos del arreglo

In [36]:
arr.dtype

dtype('int64')

# Selección e indices en Numpy


In [42]:
# crear un arreglo
arr = np.arange(0,11)

In [43]:
# desplegar el arreglo
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Selección utilizando corchetes

In [44]:
# obtener el valor del indice 8
arr[8]

8

In [45]:
# obtener los valores de un rango
arr[1:5]

array([1, 2, 3, 4])

In [46]:
#obtener los valores de otro rango
arr[2:6]

array([2, 3, 4, 5])

# Reemplazar valores

In [47]:
# reemplazar valores en un rango determinado
arr[0:5]=100

# desplegar el arreglo

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
#  Generar nuevamente el arreglo
arr = np.arange(0,11)

# desplegar
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# corte de un arreglo
slice_of_arr = arr[0:6]

# desplegar el corte
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [50]:
# cambiar valores del corte
slice_of_arr[:]=99

# desplegar los valores del corte
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [51]:
# desplegar arreglo
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
# para obtener una copia se debe hacer explicitamente
arr_copy = arr.copy()

# desplegar el arreglo copia
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indices en un arreglo 2D (matrices)

La forma general de un arreglo 2d es la siguiente **arr_2d[row][col]** o **arr_2d[row,col]**


In [53]:
# generar un arreglo 2D
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
# indices de filas
arr_2d[1]


array([20, 25, 30])

In [55]:
# Formato es arr_2d[row][col] o arr_2d[row,col]

# Seleccionar un solo elemento
arr_2d[1][0]

20

In [56]:
# Seleccionar un solo elemento
arr_2d[1,0]

20

In [57]:
# Cortes en 2D

# forma (2,2) desde la esquina superior derecha
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
#forma desde la ultima fila
arr_2d[2]

array([35, 40, 45])

In [59]:
# forma desde la ultima fila
arr_2d[2,:]

array([35, 40, 45])

In [62]:
# longitud de un arreglo
arr_length = arr_2d.shape[1]

arr_length

3

# Selección

In [63]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [65]:
bool_arr = arr>4

In [66]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [67]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [68]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])