# Numpy

### GitHub repository: https://github.com/jorgemauricio/curso_itesm

### Instructor: Jorge Mauricio

In [1]:
# librerías
import numpy as np

# Crear Numpy Arrays
## De una lista de python
Creamos el arreglo directamente de una lista o listas de python

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## Métodos

### arange

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### ceros y unos
Generar arreglos de ceros y unos

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Generar un arreglo especificando un intervalo

In [11]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### eye
Generar matrices de identidad

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
### rand
Generar un arreglo con una forma determinada de numeros con una distribución uniforme [0,1]

In [14]:
np.random.rand(2)

array([0.36888333, 0.31650473])

In [15]:
np.random.rand(5,5)

array([[0.66088805, 0.58524241, 0.58136279, 0.77666592, 0.36942507],
       [0.05818768, 0.23436678, 0.25857697, 0.40521337, 0.27391035],
       [0.30067519, 0.20129451, 0.89114266, 0.76754978, 0.69841236],
       [0.14034806, 0.96889489, 0.33414698, 0.89913417, 0.22297595],
       [0.53003281, 0.20558638, 0.98850174, 0.22465462, 0.35179924]])

### randn
Generar un arreglo con una distribucion estandar a diferencia de rand que es uniforme

In [16]:
np.random.randn(2)

array([0.94425463, 1.10061984])

In [17]:
np.random.randn(5,5)

array([[-0.99370244,  1.3719013 ,  0.40965712,  0.40113318,  0.39537323],
       [ 0.33622611, -0.20051933,  0.27647462,  0.71804366, -0.6993949 ],
       [-0.06116892,  0.9344125 , -1.91911817, -0.15426848, -0.20147199],
       [-0.13530899, -0.75791843,  1.16709492,  0.99455696,  0.81854165],
       [-0.27400909,  0.5825084 , -0.88843559, -0.34976756, -1.27893962]])

### randint
Generar numeros aleatorios en un rango determinado

In [18]:
np.random.randint(1,100)

30

In [19]:
np.random.randint(1,100,10)

array([45, 34, 65, 63, 23, 63, 74, 56, 99, 58])

### Métodos y atributos de arreglos


In [20]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr

array([30, 41,  6,  0, 38,  6, 10, 41, 15, 34])

### Reshape
Regresa el mismo arreglo pero en diferente forma

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin
Metodos para encontrar máximos y mínimos de los valores y sus indices

In [24]:
ranarr

array([30, 41,  6,  0, 38,  6, 10, 41, 15, 34])

In [25]:
ranarr.max()

41

In [26]:
ranarr.argmax()

1

In [27]:
ranarr.min()

0

In [28]:
ranarr.argmin()

3

### Shape
Atributo para desplegar la forma que tienen el arreglo

In [29]:
# Vector
arr.shape

(25,)

In [30]:
# Tomar en cuenta que se implementan dos corchetes
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [31]:
arr.reshape(1,25).shape

(1, 25)

In [32]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [33]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Despliega el tipo de dato de los objetos del arreglo

In [34]:
arr.dtype

dtype('int64')

# Selección e indices en Numpy


In [35]:
# crear un arreglo
arr = np.arange(0,11)

In [36]:
# desplegar el arreglo
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Selección utilizando corchetes

In [37]:
# obtener el valor del indice 8
arr[8]

8

In [38]:
# obtener los valores de un rango
arr[1:5]

array([1, 2, 3, 4])

In [39]:
#obtener los valores de otro rango
arr[2:6]

array([2, 3, 4, 5])

# Reemplazar valores

In [40]:
# reemplazar valores en un rango determinado
arr[0:5]=100

# desplegar el arreglo

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [41]:
#  Generar nuevamente el arreglo
arr = np.arange(0,11)

# desplegar
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# corte de un arreglo
slice_of_arr = arr[0:6]

# desplegar el corte
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [43]:
# cambiar valores del corte
slice_of_arr[:]=99

# desplegar los valores del corte
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [44]:
# desplegar arreglo
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [45]:
# para obtener una copia se debe hacer explicitamente
arr_copy = arr.copy()

# desplegar el arreglo copia
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indices en un arreglo 2D (matrices)

La forma general de un arreglo 2d es la siguiente **arr_2d[row][col]** o **arr_2d[row,col]**


In [46]:
# generar un arreglo 2D
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
# indices de filas
arr_2d[1]


array([20, 25, 30])

In [48]:
# Formato es arr_2d[row][col] o arr_2d[row,col]

# Seleccionar un solo elemento
arr_2d[1][0]

20

In [49]:
# Seleccionar un solo elemento
arr_2d[1,0]

20

In [50]:
# Cortes en 2D

# forma (2,2) desde la esquina superior derecha
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [51]:
#forma desde la ultima fila
arr_2d[2]

array([35, 40, 45])

In [52]:
# forma desde la ultima fila
arr_2d[2,:]

array([35, 40, 45])

In [53]:
# longitud de un arreglo
arr_length = arr_2d.shape[1]

arr_length

3

# Selección

In [54]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
bool_arr = arr>4

In [57]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [58]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])